# Generated by Django 2.1.7 on 2019-04-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='用户名的md5值,不用填写', max_length=255, unique=True, verbose_name='唯一ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('mobile', models.BigIntegerField(help_text='用于手机验证码登录', unique=True, verbose_name='手机')),
                ('qq', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='QQ')),
                ('weixin', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='微信')),
                ('wx_openid', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='微信openid')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人签名')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
                ('gender', models.SmallIntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('degree', models.PositiveSmallIntegerField(blank=True, choices=[(0, '学历'), (1, '高中以下'), (2, '中专／高中'), (3, '大专'), (4, '本科'), (5, '硕士'), (6, '博士')], default=0, null=True, verbose_name='学历')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('id_card', models.CharField(blank=True, max_length=32, null=True, verbose_name='身份证号或护照号')),
                ('is_active', models.BooleanField(default=True, verbose_name='账户状态')),
                ('is_staff', models.BooleanField(default=False, help_text='决定着用户是否可登录管理后台', verbose_name='staff status')),
                ('name', models.CharField(default='', max_length=32, verbose_name='真实姓名')),
                ('head_img', models.CharField(default='/static/frontend/head_portrait/logo@2x.png', max_length=128, verbose_name='个人头像')),
                ('role', models.SmallIntegerField(choices=[(0, '学生'), (1, '导师'), (2, '讲师'), (3, '管理员')], default=0, verbose_name='角色')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='可提现和使用余额')),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='备注')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '203. 账户表',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回答')),
                ('agree_number', models.IntegerField(default=0, verbose_name='点赞数')),
                ('disagree_number', models.IntegerField(default=0, verbose_name='点踩数')),
                ('answer_date', models.DateTimeField(auto_now=True, verbose_name='日期')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account', verbose_name='回答者')),
            ],
            options={
                'verbose_name_plural': '800000003. 讨论区：解答',
            },
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=512, verbose_name='评论内容')),
                ('attachment_path', models.CharField(blank=True, help_text='跟进记录的截图等', max_length=128, null=True, verbose_name='附件路径')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account', verbose_name='评论者')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Answer')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.AnswerComment', verbose_name='基于评论的评论')),
            ],
            options={
                'verbose_name_plural': '800000004. 讨论区：评论',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='标题')),
                ('article_type', models.SmallIntegerField(choices=[(0, '资讯'), (1, '视频')], default=0, verbose_name='文章类型')),
                ('brief', models.TextField(max_length=512, verbose_name='文章概要')),
                ('head_img', models.CharField(max_length=255, verbose_name='文章头贴图')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('pub_date', models.DateTimeField(verbose_name='上架日期')),
                ('offline_date', models.DateTimeField(verbose_name='下架日期')),
                ('status', models.SmallIntegerField(choices=[(0, '在线'), (1, '下线')], default=0, verbose_name='文章状态')),
                ('order', models.SmallIntegerField(default=0, help_text='文章想置顶，可以把数字调大，不要超过1000', verbose_name='权重')),
                ('vid', models.CharField(blank=True, help_text='文章类型是视频，则需要添加视频VID', max_length=128, null=True, verbose_name='视频VID')),
                ('comment_num', models.SmallIntegerField(default=0, verbose_name='评论数')),
                ('agree_num', models.SmallIntegerField(default=0, verbose_name='点赞数')),
                ('view_num', models.SmallIntegerField(default=0, verbose_name='浏览数')),
                ('collect_num', models.SmallIntegerField(default=0, verbose_name='收藏数')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('position', models.SmallIntegerField(choices=[(0, '信息流'), (1, 'banner大图'), (2, 'banner小图')], default=0, verbose_name='位置')),
            ],
            options={
                'verbose_name_plural': '3002. 深科技文章表',
            },
        ),
        migrations.CreateModel(
            name='ArticleSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='文章来源')),
            ],
            options={
                'verbose_name_plural': '3001. 深科技文章来源',
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='章节名')),
                ('chapter', models.IntegerField(verbose_name='章节号')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='章节介绍')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
            ],
            options={
                'verbose_name_plural': '10. 课程章节',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='城市码')),
                ('name', models.CharField(max_length=64, verbose_name='城市名')),
            ],
            options={
                'verbose_name_plural': '205. 城市表',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='收藏日期')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account', verbose_name='账号')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '40001. 通用收藏表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象')),
                ('content', models.TextField(max_length=1024, verbose_name='内容')),
                ('disagree_number', models.IntegerField(default=0, verbose_name='踩')),
                ('agree_number', models.IntegerField(default=0, verbose_name='赞')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论日期')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account', verbose_name='账号')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='类型')),
                ('p_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name_plural': '40002. 通用评论表',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='优惠券名')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='优惠券介绍')),
                ('coupon_type', models.SmallIntegerField(choices=[(0, '通用券'), (1, '折扣券'), (2, '满减券')], verbose_name='券类型')),
                ('money_equivalent_value', models.IntegerField(blank=True, null=True, verbose_name='等值货币')),
                ('off_percent', models.PositiveIntegerField(blank=True, help_text='只针对折扣券，例7.9折，写79', null=True, verbose_name='折扣百分比')),
                ('minimum_consume', models.PositiveIntegerField(default=0, help_text='仅在满减券时填写此字段', verbose_name='最低消费')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='通用卷不用绑定课程', null=True, verbose_name='课程id')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='优惠券数量')),
                ('open_date', models.DateField(verbose_name='优惠券领取开始时间')),
                ('close_date', models.DateField(verbose_name='优惠券领取结束时间')),
                ('valid_begin_date', models.DateField(blank=True, null=True, verbose_name='有效期开始时间')),
                ('valid_end_date', models.DateField(blank=True, null=True, verbose_name='有效期结束时间')),
                ('coupon_valid_days', models.PositiveIntegerField(blank=True, help_text='自从券被领取时开始算起', null=True, verbose_name='优惠卷有效期(天)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='课程类型')),
            ],
            options={
                'verbose_name_plural': '500001. 优惠卷类型',
            },
        ),
        migrations.CreateModel(
            name='CouponRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_number', models.CharField(max_length=64, unique=True, verbose_name='优惠卷编号')),
                ('status', models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已过期')], default=0, verbose_name='优惠卷状态')),
                ('get_time', models.DateTimeField(help_text='用户领取时间', verbose_name='领取时间')),
                ('used_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
            ],
            options={
                'verbose_name_plural': '500002. 优惠卷记录',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='课程名')),
                ('image', models.CharField(max_length=255, verbose_name='课程图片')),
                ('course_type', models.SmallIntegerField(choices=[(0, '付费'), (1, 'VIP专享'), (2, '学位课程模块')], verbose_name='专题课类型')),
                ('brief', models.TextField(max_length=2048, verbose_name='课程简介')),
                ('level', models.SmallIntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=2, verbose_name='难度')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='课程发布日期')),
                ('period', models.PositiveIntegerField(default=7, verbose_name='建议学习周期(days)')),
                ('order', models.IntegerField(help_text='从上一个课程数字往后排', verbose_name='课程顺序')),
                ('attachment_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='课程课件路径')),
                ('status', models.SmallIntegerField(choices=[(0, '上线'), (1, '下线'), (2, '预上线')], default=0, verbose_name='课程状态')),
                ('template_id', models.SmallIntegerField(default=1, verbose_name='前端模板ID')),
            ],
            options={
                'verbose_name_plural': '06. 专题课程表',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='课程类型')),
            ],
            options={
                'verbose_name_plural': '01. 课程大表',
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(verbose_name='课时')),
                ('course_slogan', models.CharField(blank=True, max_length=125, null=True, verbose_name='口号')),
                ('video_brief_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='课程简介视频')),
                ('why', models.CharField(max_length=255, verbose_name='为什么报课程')),
                ('what_to_study_brief', models.TextField(verbose_name='将会学到什么')),
                ('career_improvement', models.TextField(verbose_name='此项目如何有助于我的职业生涯')),
                ('prerequisite', models.TextField(max_length=1024, verbose_name='课程先修条件')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Course', verbose_name='课程')),
                ('recommend_courses', models.ManyToManyField(blank=True, related_name='re_course', to='luffyapi.Course', verbose_name='相关推荐课程')),
            ],
            options={
                'verbose_name_plural': '07. 专题课程详情表',
            },
        ),
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='显示顺序')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.CharField(max_length=2048, verbose_name='大纲内容')),
                ('course_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.CourseDetail', verbose_name='课程详情')),
            ],
            options={
                'verbose_name_plural': '09. 大纲表',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_date', models.DateField(verbose_name='推荐交作业日期')),
            ],
            options={
                'verbose_name_plural': '15. 课程模块计划表（学位课）',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='课名')),
                ('order', models.IntegerField(help_text='建议每个课时之间空1至2个值，以备后续插入课时', verbose_name='课序')),
                ('section_type', models.SmallIntegerField(choices=[(0, '文档'), (1, '视频'), (2, '练习')], default=1, verbose_name='课类型')),
                ('section_link', models.CharField(help_text='如果是视频类型，填写vid,如果是文档，填link', max_length=255, verbose_name='连接文件')),
                ('video_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='视频时长')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('free_trail', models.BooleanField(default=False, verbose_name='是否可试看')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Chapters', verbose_name='章节')),
            ],
            options={
                'verbose_name_plural': '11. 课节表',
            },
        ),
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='子课程类型')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.CourseCategory', verbose_name='所属大分类')),
            ],
            options={
                'verbose_name_plural': '02. 课程子表',
            },
        ),
        migrations.CreateModel(
            name='DegreeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='学位课程名')),
                ('course_img', models.CharField(max_length=255, verbose_name='课程示图')),
                ('brief', models.TextField(verbose_name='学位课程简介')),
                ('total_scholarship', models.PositiveIntegerField(default=40000, verbose_name='总奖学金(里贝)')),
                ('mentor_compensation_bonus', models.PositiveIntegerField(default=15000, verbose_name='本课程的导师辅导费用(里贝)')),
                ('period', models.PositiveIntegerField(default=150, verbose_name='建议学习周期（days)')),
                ('prerequisite', models.TextField(max_length=1024, verbose_name='课程先修要求')),
            ],
            options={
                'verbose_name_plural': '03. 学位课程表',
            },
        ),
        migrations.CreateModel(
            name='DegreeRegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_company', models.CharField(max_length=64)),
                ('current_position', models.CharField(max_length=64)),
                ('current_salary', models.IntegerField()),
                ('work_experience', models.IntegerField()),
                ('open_module', models.BooleanField(default=True, verbose_name='是否开通第1模块')),
                ('stu_specified_mentor', models.CharField(blank=True, max_length=32, null=True, verbose_name='学员自行指定的导师名')),
                ('study_plan', models.SmallIntegerField(choices=[(0, '1-2小时/天'), (1, '2-3小时/天'), (2, '3-5小时/天'), (3, '5小时+/天')], default=1)),
                ('why_take_this_course', models.TextField(max_length=1024, verbose_name='报此课程原因')),
                ('why_choose_us', models.TextField(max_length=1024, verbose_name='为何选路飞')),
                ('your_expectation', models.TextField(max_length=1024, verbose_name='你的期待')),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '18. 报名表（学位课）',
            },
        ),
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('valid_begin_date', models.DateField(verbose_name='有效期开始自')),
                ('valid_end_date', models.DateField(verbose_name='有效期结束至')),
                ('status', models.SmallIntegerField(choices=[(0, '已开通'), (1, '已过期')], default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account')),
                ('course', models.ForeignKey(limit_choices_to=models.Q(_negated=True, course_type=2), on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Course')),
            ],
            options={
                'verbose_name_plural': '19. 报名专题课',
            },
        ),
        migrations.CreateModel(
            name='EnrolledDegreeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('valid_begin_date', models.DateField(blank=True, null=True, verbose_name='有效期开始自')),
                ('valid_end_date', models.DateField(blank=True, null=True, verbose_name='有效期结束至')),
                ('study_status', models.SmallIntegerField(choices=[(0, '在学中'), (1, '休学中'), (2, '已毕业'), (3, '超时结业'), (4, '未开始')], default=0)),
                ('mentor_fee_balance', models.PositiveIntegerField(help_text='这个学员的导师费用，每有惩罚，需在此字段同时扣除', verbose_name='导师费用余额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account')),
                ('degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.DegreeCourse')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 1}, null=True, on_delete='', related_name='my_students', to='luffyapi.Account', verbose_name='导师')),
            ],
            options={
                'verbose_name_plural': '17. 报名学位课',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='标题')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系方式')),
                ('feedback_type', models.SmallIntegerField(choices=[(0, '网站优化建议'), (1, '烂!我想吐槽'), (2, '网站bug反馈')], default=0, verbose_name='反馈类型')),
                ('content', models.TextField(max_length=1024, verbose_name='反馈内容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
            ],
            options={
                'verbose_name_plural': '208. 反馈表',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='作业题目')),
                ('order', models.SmallIntegerField(help_text='同一课程的每个作业之前的order值间隔1-2个数', verbose_name='作业顺序')),
                ('homework_type', models.SmallIntegerField(choices=[(0, '作业'), (1, '模块通关考核')], default=0, verbose_name='作业类型')),
                ('requirement', models.CharField(max_length=1024, verbose_name='作业需求')),
                ('threshold', models.TextField(max_length=1024, verbose_name='踩分点')),
                ('recommend_period', models.PositiveSmallIntegerField(default=7, verbose_name='推荐完成周期(天)')),
                ('scholarship', models.PositiveSmallIntegerField(verbose_name='为该作业分配的奖学金(贝里)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='注意提示')),
                ('enabled', models.BooleanField(default=True, help_text='本作业如果后期不需要了，不想让学员看到，可以设置为False')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Chapters', verbose_name='章节')),
            ],
            options={
                'verbose_name_plural': '12. 章节作业',
            },
        ),
        migrations.CreateModel(
            name='HomeworkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True, choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (70, 'B-'), (60, 'C+'), (50, 'C'), (40, 'C-'), (-1, 'D'), (0, 'N/A'), (-100, 'COPY')], null=True, verbose_name='分数')),
                ('mentor_comment', models.TextField(blank=True, null=True, verbose_name='导师批注')),
                ('status', models.SmallIntegerField(choices=[(0, '待批改'), (1, '已通过'), (2, '不合格')], default=0, verbose_name='作业状态')),
                ('submit_num', models.SmallIntegerField(default=0, verbose_name='提交次数')),
                ('correct_date', models.DateTimeField(blank=True, null=True, verbose_name='备注日期')),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='作业提交日期')),
                ('check_date', models.DateTimeField(blank=True, null=True, verbose_name='批改日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='提交日期')),
                ('reward_status', models.SmallIntegerField(default=0, verbose_name='作业记录奖惩状态')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.HomeWork')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='my_stu_homework_record', to='luffyapi.Account', verbose_name='导师')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.EnrolledDegreeCourse', verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '13. 作业',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='行业代码')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='行业名称')),
            ],
            options={
                'verbose_name_plural': '206. 行业表',
            },
        ),
        migrations.CreateModel(
            name='MentorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='导师组名')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='简介brief')),
                ('mentors', models.ManyToManyField(limit_choices_to={'role': 1}, to='luffyapi.Account', verbose_name='组员')),
            ],
            options={
                'verbose_name_plural': '14. 导师组',
            },
        ),
        migrations.CreateModel(
            name='OftenAskedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='常见问题')),
                ('answer', models.CharField(max_length=255, verbose_name='答案')),
                ('object_id', models.IntegerField(help_text='多个表的对象主键', verbose_name='关联对象ID')),
                ('content_type', models.ForeignKey(help_text='外键引用ContentType的主键', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='所属表的类型')),
            ],
            options={
                'verbose_name_plural': '08. 常见问题表',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.SmallIntegerField(choices=[(0, '微信'), (1, '支付宝'), (2, '优惠码'), (3, '贝里')])),
                ('payment_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='支付第3方订单号')),
                ('order_number', models.CharField(max_length=128, unique=True, verbose_name='订单号')),
                ('actual_amount', models.FloatField(verbose_name='实付金额')),
                ('status', models.SmallIntegerField(choices=[(0, '交易成功'), (1, '待支付'), (2, '退费申请中'), (3, '已退费'), (4, '主动取消'), (5, '超时取消')], verbose_name='状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='订单取消时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account', verbose_name='账号')),
            ],
            options={
                'verbose_name_plural': '70000001. 订单表',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('original_price', models.FloatField(verbose_name='课程原价')),
                ('price', models.FloatField(verbose_name='折后价格')),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_period_display', models.CharField(max_length=32, verbose_name='有效期显示')),
                ('valid_period', models.PositiveIntegerField(verbose_name='有效期(days)')),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Order')),
            ],
            options={
                'verbose_name_plural': '70000002. 订单详细',
            },
        ),
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, '1天'), (3, '3天'), (7, '1周'), (14, '2周'), (30, '1个月'), (60, '2个月'), (90, '3个月'), (180, '6个月'), (210, '12个月'), (540, '18个月'), (720, '24个月')], verbose_name='学习周期')),
                ('price', models.FloatField()),
                ('object_id', models.IntegerField(verbose_name='课程对象')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='对应类型')),
            ],
            options={
                'verbose_name_plural': '20. 价格策略表',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='职业代码')),
                ('name', models.CharField(max_length=64, verbose_name='职业名称')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Industry', verbose_name='所属行业')),
            ],
            options={
                'verbose_name_plural': '207. 职业表',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='省代码')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='省名称')),
            ],
            options={
                'verbose_name_plural': '204. 省份表',
            },
        ),
        migrations.CreateModel(
            name='QACounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('data_type', models.SmallIntegerField(choices=[(0, '点赞'), (1, '踩'), (2, '同问')])),
                ('date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': '800000005. 问题和回答的赞同数量统计',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='问题概要')),
                ('question_type', models.SmallIntegerField(choices=[(0, '专题课程问题'), (1, '学位课程问题')], default=0, verbose_name='来源')),
                ('content', models.TextField(max_length=1024, verbose_name='问题内容')),
                ('enquiries_count', models.IntegerField(default=0, verbose_name='同问者计数')),
                ('attachment_path', models.CharField(blank=True, help_text='问题记录的截图等', max_length=128, null=True, verbose_name='附件路径')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, '待解答'), (1, '已解答'), (2, '已关闭')], default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account', verbose_name='提问者')),
                ('course_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.CourseSection')),
                ('degree_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.DegreeCourse')),
            ],
            options={
                'verbose_name_plural': '800000002. 讨论区：课程提问',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_percent', models.PositiveIntegerField(help_text='只填写百分整数值，如90，代表90%', verbose_name='完成学位时间占比')),
                ('value', models.PositiveIntegerField(verbose_name='奖学金数额')),
                ('degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.DegreeCourse', verbose_name='学位课程')),
            ],
            options={
                'verbose_name_plural': '05. 学位奖学金表',
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.IntegerField(verbose_name='金额(贝里)')),
                ('received_score', models.IntegerField(default=0, help_text='仅奖励用', verbose_name='实际到账金额贝里)')),
                ('balance', models.PositiveIntegerField(verbose_name='奖金余额(贝里)')),
                ('maturity_date', models.DateField(verbose_name='成熟日期(可提现日期)')),
                ('applied', models.BooleanField(default=False, help_text='奖赏纪录是否已被执行', verbose_name='是否已被执行')),
                ('applied_date', models.DateTimeField(blank=True, null=True, verbose_name='事件生效日期')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='事件触发日期')),
                ('memo', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account', verbose_name='被执行人')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('degree_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.DegreeCourse', verbose_name='关联学位课程')),
            ],
            options={
                'verbose_name_plural': '6000002. 奖惩记录',
            },
        ),
        migrations.CreateModel(
            name='ScoreRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.SmallIntegerField(choices=[(0, '未按时交作业'), (1, '未及时批改作业'), (2, '作业成绩'), (3, '未在规定时间内对学员进行跟进'), (4, '未在规定时间内回复学员问题'), (5, '收到学员投诉'), (6, '导师相关'), (7, '学位奖学金')], verbose_name='积分规则')),
                ('score_type', models.SmallIntegerField(choices=[(0, '奖励'), (1, '惩罚'), (2, '初始分配')], default=0, verbose_name='奖惩')),
                ('score', models.IntegerField(help_text='扣分数与贝里相等,若为0则代表规则的值可以从别处取得')),
                ('memo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '6000001. 奖惩规则',
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='开通日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('status', models.SmallIntegerField(choices=[(2, '在学'), (1, '未开通'), (0, '已完成')], default=1)),
                ('course_module', models.ForeignKey(limit_choices_to={'course_type': 2}, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Course', verbose_name='学位模块')),
                ('enrolled_degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.EnrolledDegreeCourse')),
            ],
            options={
                'verbose_name_plural': '16. 学习记录表（报名学位课程后，每个模块会立刻生成一条学习纪录）',
            },
        ),
        migrations.CreateModel(
            name='StuFollowUpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_tool', models.SmallIntegerField(choices=[(0, 'QQ'), (1, '微信'), (2, '电话'), (3, '系统通知')], default=1)),
                ('record', models.TextField(verbose_name='跟进记录')),
                ('attachment_path', models.CharField(blank=True, help_text='跟进记录的截图等', max_length=128, null=True, verbose_name='附件路径')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('enrolled_degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.EnrolledDegreeCourse', verbose_name='学生')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='luffyapi.Account', verbose_name='导师')),
            ],
            options={
                'verbose_name_plural': '800000001. 学员跟进记录',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.SmallIntegerField(choices=[(0, '文章标签'), (1, '课程评价标签'), (2, '用户感兴趣技术标签')], verbose_name='标签类型')),
                ('name', models.CharField(max_length=64, verbose_name='标签名')),
            ],
            options={
                'verbose_name_plural': '40003. 标签集合表',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='老师名')),
                ('role', models.SmallIntegerField(choices=[(0, '讲师'), (1, '导师')], default=0, verbose_name='老师角色')),
                ('title', models.CharField(max_length=64, verbose_name='职位/职称')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='签名')),
                ('image', models.CharField(max_length=255, verbose_name='老师照片')),
                ('brief', models.CharField(max_length=1024, verbose_name='老师简介')),
            ],
            options={
                'verbose_name_plural': '04. 老师表',
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='金额')),
                ('transaction_type', models.SmallIntegerField(choices=[(0, '收入'), (1, '支出'), (2, '退款'), (3, '提现')])),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象')),
                ('transaction_number', models.CharField(max_length=128, unique=True, verbose_name='流水号')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Account')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': '70000003. 贝里交易记录',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '201. 学城用户表',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, verbose_name='token')),
                ('expired', models.DateTimeField(auto_now_add=True, verbose_name='有效期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '202. 用户认证token表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('name', 'tag_type')},
        ),
        migrations.AlterUniqueTogether(
            name='scorerule',
            unique_together={('rule', 'score_type')},
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='score_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.ScoreRule', verbose_name='关联规则'),
        ),
        migrations.AddField(
            model_name='enrolleddegreecourse',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.OrderDetail'),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.OrderDetail'),
        ),
        migrations.AddField(
            model_name='degreeregistrationform',
            name='enrolled_degree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.EnrolledDegreeCourse'),
        ),
        migrations.AddField(
            model_name='degreecourse',
            name='teachers',
            field=models.ManyToManyField(to='luffyapi.Teacher', verbose_name='课程老师'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.HomeWork'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='study_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.StudyRecord'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='teachers',
            field=models.ManyToManyField(to='luffyapi.Teacher', verbose_name='任课老师'),
        ),
        migrations.AddField(
            model_name='course',
            name='degree_course',
            field=models.ForeignKey(blank=True, help_text='专题课程所属的学位课程,这里这填写关联的学位课程，可为空，表示不是学位课程', null=True, on_delete=django.db.models.deletion.SET_NULL, to='luffyapi.DegreeCourse', verbose_name='学位课程'),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.CourseSubCategory', verbose_name='子课程分类'),
        ),
        migrations.AddField(
            model_name='couponrecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.UserInfo', verbose_name='所属账户'),
        ),
        migrations.AddField(
            model_name='couponrecord',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Coupon', verbose_name='优惠券类型'),
        ),
        migrations.AddField(
            model_name='couponrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Order', verbose_name='使用的订单'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Province', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='chapters',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.ArticleSource', verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='luffyapi.Tags', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Question', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.City', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='account',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Profession', verbose_name='职位信息'),
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.ManyToManyField(blank=True, to='luffyapi.Tags', verbose_name='感兴趣的标签'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.UserInfo', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together={('enrolled_degree_course', 'course_module')},
        ),
        migrations.AlterUniqueTogether(
            name='qacounter',
            unique_together={('content_type', 'object_id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='pricepolicy',
            unique_together={('object_id', 'content_type', 'price')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='oftenaskedquestion',
            unique_together={('question', 'object_id', 'content_type')},
        ),
        migrations.AlterUniqueTogether(
            name='homeworkrecord',
            unique_together={('homework', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('chapter', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='enrolleddegreecourse',
            unique_together={('account', 'degree_course')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('chapter', 'section_link')},
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('study_record', 'homework')},
        ),
        migrations.AlterUniqueTogether(
            name='courseoutline',
            unique_together={('course_detail', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('content_type', 'object_id', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='chapters',
            unique_together={('course', 'chapter')},
        ),
    ]
