# Generated by Django 2.1.7 on 2019-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffyapi', '0002_auto_20190121_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '上线'), (1, '下线'), (2, '预上线')], default=0, verbose_name='课程状态'),
        ),
    ]
