# Generated by Django 2.0.7 on 2018-12-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffyapi', '0002_test_test2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='test',
        ),
        migrations.AddField(
            model_name='test2',
            name='test',
            field=models.ManyToManyField(to='luffyapi.Test'),
        ),
    ]
