# Generated by Django 2.0.7 on 2019-01-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luffyapi', '0004_chapters_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, verbose_name='token')),
                ('expired', models.DateTimeField(auto_now_add=True, verbose_name='有效期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luffyapi.UserInfo', verbose_name='用户')),
            ],
        ),
    ]
