# Generated by Django 2.1.7 on 2019-04-04 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luffyapi', '0005_remove_couponrecord_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luffyapi.Order', verbose_name='使用的订单'),
        ),
    ]
